- name: provision instance for Apache
  hosts: localhost
  connection: local
  remote_user: ec2-user
  gather_facts: false
- name: install Apache
  hosts: launched
  remote_user: ec2-user
  yum:
   name: httpd
   state: installed
