---
- hosts: localhost
  connection: local
  remote_user: ec2-user
  become: True
  become_method: sudo
  gather_facts: True
  tasks:
    - name: Updating instance
      yum: 
        name: httpd
        state: installed
