---
- name: Copy the jinja template to target
  hosts: tomcat
  tasks: 
  - name: install httpd
    yum:
     name: httpd
     state: present
  - name: use index file template
    template:
     src: index.j2
     dest: /var/www/html/index.html
