---
- hosts: all
  become_user: root
  tasks:
    - name: Adding Group
      group:
        name={{ item }}
        state=present
      with_items:
        - demogroup
        - demogroup1
        - demogroup2
      tags: add_new_group

    - name: Adding User
      user:
        name={{ item }}
        state=present
        group=demogroup
        password="Ikpkas28"
        shell=/bin/bash
      with_items:
        - demouser1
        - demouser2
        - demouser3
      tags: add_new_user

    - name: Generating ssh keys for a user
      user:
        name={{ item }}
        generate_ssh_key=yes
        ssh_key_bits=4096
        ssh_key_file=.ssh/id_rsa
        with_items:
        - demouser1
        - demouser2
        - demouser3
      tags: generate_ssh_keys

    - name: Copy public keys
      authorized_key:
       user: demouser1
       state: present
       key: "{{ lookup('file', '/home/demouser1/.ssh/id_rsa.pub') }}"
      tags: copy_pub_key

    - name: Delete Some user
      user:
        name={{ item }}
        state=absent
      with_items:
        - demouser3
        - demouser4
      tags: remove_user

    - name: Delete some group
      group:
         name={{ item }}
         state=absent
      with_items:
         - demogroup1
         - demogroup2
      tags: remove_group