pipeline{
    agent any
    stages{
        stage('Test'){
            steps{
                echo "Testing the code - phase-1"
                echo "Testing the code - phase-2"
            }
        }
        stage('Build'){
            steps{
                echo "Building the code"
            }
        }
        stage('Release'){
            steps{
                echo "Releasing the code"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploying the code"
            }
        }
    }
    post{
        always {
            echo "Build run"
        }
        failure {
            echo "Build failed!"
        }
        success {
            echo "Build Succeeded!"
        }
        unstable {
            echo "Build Unstable!"
        }
        changed {
            echo "Build state is chnaged."
        }
    }
}