ansible_user: "root"
ansible_ssh_private_key_file: "/Users/vikas.gupta/.ssh/id_rsa"
#ansible_user: "{{ lookup('env', 'SECRET_CLOUD_BASTION_USER') or 'centos' }}"
#nsible_ssh_private_key_file: "{{ lookup('env', 'SECRET_CLOUD_BASTION_KEY_FILE') or 'my-key.pem' }}"


