pipeline{
    agent any
    stages{
        stage('Test'){
            steps{
                echo "testing the code"
            }
        }
        stage('Build'){
            steps{
                echo "Building the Code"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploy the Code"
            }
        }
    }
    post{
        always {
            echo "Buils run"
        }
        failure {
            echo "Build failed"
        }
        success {
            echo "build Successful"
        }
        unstable {
            echo "build unstable"
        }
        chnaged {
            echo "build state is changed"
        }
    }
}
