pipeline{
    agent any
    stages{
        stage('Test'){
            steps{
                echo "testing the code"
            }
        }
        stage('Build'){
            steps{
                echo "Building the Code"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploy the Code"
            }
        }
    }
}
