Pipline{
    agent any
    Stages{
        Stage('Test'){
            Steps{
                echo "testing the code"
            }
        }
        Stage('Build'){
            Steps{
                echo "Building the Code"
            }
        }
        Stage('Deploy'){
            Steps{
                echo "Deploy the Code"
            }
        }
    }
}